### ISSUE TITLE
Include the v6.0.0 of sendinblue/APIv3-php-library

### ISSUE THREAD

**Issue by ghost** [sendinblue/APIv3-symfony-bundle#8]
Hello
Can you include the v6.0.0 of sendinblue/APIv3-php-library in this bundle ?

Thanks !

Poke @MatTheCat 🐱

**Comment by MatTheCat** [comment]
v6 introduced some BC breaks; I'm not sure how to design the configuration yet.

**Comment by MatTheCat** [comment]
Seems the only thing a bundle could simplify now is calling `Configuration::setApiKey`. Now it is simpler to just declare endpoints as services, like

```yaml
services:
    SendinBlue\Client\Configuration:
        calls:
            - method: setApiKey
              arguments:
                  - api-key
                  - '%your_api_key%'

    SendinBlue\Client\Api\SMTPApi: ~
``` 

So I think this bundle will only support sendinblue/api-v3-sdk >=2 <6.
